[workspace]
members = ["crates/tsz-cli", "crates/tsz-compiler"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "UNLICENSED"

[workspace.lints.rust]
unsafe_code = "forbid"

